eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/
server:
  port: 8182
spring:
  application:
    name: fungo-game-gateway
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://47.104.87.10:9411/

## 关闭安全限制
##management:
##  security:
##    enabled: false
#
# # 路由配置
#zuul:
#  routes:
#    api-a:
#      path: /biz/**
#      serviceId: ncyp-company-biz
#    api-b:
#      path: /agreement/**
#      serviceId: ncyp-company-triagreement
 # 配置超时时间断路器才有效果（加入Zuul）
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
