eureka:
  client:
    serviceUrl:
      defaultZone:  http://47.92.146.75:8761/eureka/
server:
  port: 8182
spring:
  application:
    name: fungo-game-gateway
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://47.104.87.10:9411/

## 关闭安全限制
#management:
#  security:
#    enabled: false
#
# 路由配置
zuul:
  routes:
    fungo-game-system:
      path: /system/**
      serviceId: fungo-game-system
    fungo-game-games:
      path: /games/**
      serviceId: fungo-game-games
 # 配置超时时间断路器才有效果（加入Zuul）
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
