server:
  port: 8182
  #port: 8183

#--------------------------------------------------------------------------------------------------------------
eureka:
  client:
    #eureka client刷新本地缓存时间
    #默认30s
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://fungoEurekaAdmin:9140f6ad68d1e@172.17.18.228:8762/eureka/,http://fungoEurekaAdmin:9140f6ad68d1e@172.17.18.227:8761/eureka/

  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    #EurekaClient 向注册中心发送心跳的时间间隔，（单位：秒）客户端告诉注册服务端自己会按照该规则发送心跳
    lease-renewal-interval-in-seconds: 5
    #EurekaServer在收到最后一次心跳后等待的时间上限，（单位：秒），超过则剔除。客户端告诉注册服务端自己会按照该规则发送心跳
    lease-expiration-duration-in-seconds: 10


#-----------------------------------------------------------------------------------------------------
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          strategy: Semaphore    #隔离策略，默认是Thread, 可选Thread｜Semaphore
          thread:
            timeoutInMilliseconds: 60000  #命令执行超时时间，默认1000msms



ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 150000
  #eureka客户端ribbon刷新时间
  #默认30s
  ServerListRefreshInterval: 1000
#-----------------------------------------------------------------------------------------------------
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

#-----------------------------------------------------------------------------------------------------



#-------------------声明接口依赖的服务名----------------------
fungoServer:
    commmunity.uri: lb://FUNGO-GAME-COMMUNITY
    system.uri: lb://FUNGO-GAME-SYSTEM
    game.uri: lb://FUNGO-GAME-GAMES

#-----------------------------------------------------------------------------------------------------
spring:

  application:
    name: fungo-game-gateway
  sleuth:
    sampler:
      percentage: 1.0

  # 路由配置
  cloud:
    client:
      ipAddress: 172.17.18.227
      #ipAddress: 172.17.18.228
    gateway:
      default-filters:
      discovery:
        locator:
          enabled: true



      #---------------url映射--------------------
      #-------------社区------------------------

      routes:
      - id:fungo-game-commmunity-1:
        uri: ${fungoServer.commmunity.uri}
        predicates:
        - Path=/api/content/communitys
      - id:fungo-game-commmunity-2:
        uri: ${fungoServer.commmunity.uri}
        predicates:
        - Path=/api/content/community/**
      - id:fungo-game-commmunity-3:
        uri: ${fungoServer.commmunity.uri}
        predicates:
        - Path=/api/content/comment
      - id:fungo-game-commmunity-4:
        uri: ${fungoServer.commmunity.uri}
        predicates:
        - Path=/api/content/comment/**
      - id:fungo-game-commmunity-5:
        uri: ${fungoServer.commmunity.uri}
        predicates:
        - Path=/api/content/message/**
      - id:fungo-game-commmunity-6:
        uri: ${fungoServer.commmunity.uri}
        predicates:
        - Path=/api/content/comments
      - id:fungo-game-commmunity-7:
        uri: ${fungoServer.commmunity.uri}
        predicates:
        - Path=/api/content/mood
      - id:fungo-game-commmunity-8:
        uri: ${fungoServer.commmunity.uri}
        predicates:
        - Path=/api/content/mood/**
      - id:fungo-game-commmunity-9:
        uri: ${fungoServer.commmunity.uri}
        predicates:
        - Path=/api/content/post
      - id:fungo-game-commmunity-10:
        uri: ${fungoServer.commmunity.uri}
        predicates:
        - Path=/api/content/post/**
      - id:fungo-game-commmunity-11:
        uri: ${fungoServer.commmunity.uri}
        predicates:
        - Path=/api/content/posts
      - id:fungo-game-commmunity-12:
        uri: ${fungoServer.commmunity.uri}
        predicates:
        - Path=/api/amwaywall/postlist
      - id:fungo-game-commmunity-13:
        uri: ${fungoServer.commmunity.uri}
        predicates:
        - Path=/api/recommend/moods
      - id:fungo-game-commmunity-17:
        uri: ${fungoServer.commmunity.uri}
        predicates:
        - Path=/api/content/reply
      - id:fungo-game-commmunity-18:
        uri: ${fungoServer.commmunity.uri}
        predicates:
        - Path=/api/content/replys
      - id:fungo-game-commmunity-19:
        uri: ${fungoServer.commmunity.uri}
        predicates:
        - Path=/api/search/communitys
      - id:fungo-game-commmunity-19:
        uri: ${fungoServer.commmunity.uri}
        predicates:
        - Path=/api/search/posts
      - id:fungo-game-community-20:
        uri: ${fungoServer.commmunity.uri}
        predicates:
        - Path=/api/search/posts/games

        #*****************游戏开始************************************
      - id:fungo-game-games-0:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/developer/gemeAnalyze

      - id:fungo-game-games-1:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/developer/gameHistory

      - id:fungo-game-games-2:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/content/evaluation

      - id:fungo-game-games-3:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/content/evaluation/**

      - id:fungo-game-games-4:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/content/evaluations

      - id:fungo-game-games-5:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/content/anliEvaluation/**

      - id:fungo-game-games-7:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/content/games

      - id:fungo-game-games-8:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/recommend/tag/game

      - id:fungo-game-games-9:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/content/game/package

      - id:fungo-game-games-10:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/content/game/recenteva

      - id:fungo-game-games-11:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/content/game/collections

      - id:fungo-game-games-12:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/content/game/items

      - id:fungo-game-games-13:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/content/gameList

      - id:fungo-game-games-15:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/gamereleaselog

      - id:fungo-game-games-16:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/game/**

      - id:fungo-game-games-18:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/gameSurveyRel

      - id:fungo-game-games-19:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/gameEvaluation

      - id:fungo-game-games-20:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/mk/**

      - id:fungo-game-games-21:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/tools/game/list/**

      - id:fungo-game-games-22:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/recommend/topic

      - id:fungo-game-games-23:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/amwaywall

      - id:fungo-game-games-24:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/amwaywall/list

      - id:fungo-game-games-25:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/recommend/pc/gamegroup

      - id:fungo-game-games-26:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/recommend/pc/groupdetail/**

      - id:fungo-game-games-27:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/make/game

      - id:fungo-game-games-28:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/make/cancel

      - id:fungo-game-games-29:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/make/bindingAppleID

      - id:fungo-game-games-30:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/make/game/clause

      - id:fungo-game-games-31:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/make/game/help

      - id:fungo-game-games-32:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/make/game/check

      - id:fungo-game-games-33:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/make/game/agree

      - id:fungo-game-games-34:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/invite/game

      - id:fungo-game-games-35:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/invite/cancel

      - id:fungo-game-games-36:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/mine/gameList

      - id:fungo-game-games-37:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/mine/evaluationList

      - id:fungo-game-games-38:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/search/games

      - id:fungo-game-games-39:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/tag/taglist

      - id:fungo-game-games-40:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/tag/game/taglist

      - id:fungo-game-games-41:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/tag/game/addtag

      - id:fungo-game-games-42:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/tag/game/addattitude

      - id:fungo-game-games-43:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/tag/hotlist

      - id:fungo-game-games-44:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/tag/taglist/selected


      - id:fungo-game-games-6:
        uri:  ${fungoServer.game.uri}
        predicates:
        - Path=/api/content/game/**

      - id:fungo-game-games-45:
        uri: ${fungoServer.game.uri}
        predicates:
        - Path=/api/tag/listPostTag

      - id:fungo-game-games-46:
        uri: ${fungoServer.game.uri}
        predicates:
        - Path=/api/content/viewGames

        #      *****************游戏2019-05-20结束************************************


      #-------------系统------------------------
      - id:fungo-game-system-1:
        uri: ${fungoServer.system.uri}
        predicates:
        - Path=/api/action/**


      - id:fungo-game-system-2:
        uri:  ${fungoServer.system.uri}
        predicates:
        - Path=/api/report/**

      - id:fungo-game-system-3:
        uri:  ${fungoServer.system.uri}
        predicates:
        - Path=/api/user/**

      - id:fungo-game-system-4:
        uri:  ${fungoServer.system.uri}
        predicates:
        - Path=/api/config/**



      - id:fungo-game-system-6:
        uri:  ${fungoServer.system.uri}
        predicates:
        - Path=/api/checkupdate/**

      - id:fungo-game-system-7:
        uri:  ${fungoServer.system.uri}
        predicates:
        - Path=/api/checkappupdate/**

      - id:fungo-game-system-8:
        uri:  ${fungoServer.system.uri}
        predicates:
        - Path=/api/checkiosupdate/**

      - id:fungo-game-system-9:
        uri:  ${fungoServer.system.uri}
        predicates:
        - Path=/api/about/**

      - id:fungo-game-system-10:
        uri:  ${fungoServer.system.uri}
        predicates:
        - Path=/api/starInfo/**

      - id:fungo-game-system-11:
        uri:  ${fungoServer.system.uri}
        predicates:
        - Path=/api/trait/**

      - id:fungo-game-system-12:
        uri:  ${fungoServer.system.uri}
        predicates:
        - Path=/api/common/**

      - id:fungo-game-system-13:
        uri:  ${fungoServer.system.uri}
        predicates:
        - Path=/api/mine/initrank/**

      - id:fungo-game-system-14:
        uri:  ${fungoServer.system.uri}
        predicates:
        - Path=/api/developer/**

      - id:fungo-game-system-15:
        uri:  ${fungoServer.system.uri}
        predicates:
        - Path=/api/inittaskhonor/**

      - id:fungo-game-system-16:
        uri:  ${fungoServer.system.uri}
        predicates:
        - Path=/api/push/**

      - id:fungo-game-system-17:
        uri:  ${fungoServer.system.uri}
        predicates:
        - Path=/api/sys/**

      - id:fungo-game-system-18:
        uri:  ${fungoServer.system.uri}
        predicates:
        - Path=/api/rank/**

      - id:fungo-game-system-19:
        uri:  ${fungoServer.system.uri}
        predicates:
        - Path=/api/vd/**

      - id:fungo-game-system-21:
        uri:  ${fungoServer.system.uri}
        predicates:
        - Path=/api/recommend/index

      - id:fungo-game-system-22:
        uri:  ${fungoServer.system.uri}
        predicates:
        - Path=/api/mall/**

      - id:fungo-game-system-23:
        uri:  ${fungoServer.system.uri}
        predicates:
        - Path=/api/advert

      - id:fungo-game-system-24:
        uri:  ${fungoServer.system.uri}
        predicates:
        - Path=/api/adt/bnr

      - id:fungo-game-system-25:
        uri:  ${fungoServer.system.uri}
        predicates:
        - Path=/api/recommend/discover

      - id:fungo-game-system-26:
        uri:  ${fungoServer.system.uri}
        predicates:
        - Path=/api/upload/**

      - id:fungo-game-system-27:
        uri:  ${fungoServer.system.uri}
        predicates:
        - Path=/api/invite/users



      - id:fungo-game-commmunity-14:
        uri: ${fungoServer.commmunity.uri}
        predicates:
        - Path=/api/recommend/**

      - id:fungo-game-system-20:
        uri:  ${fungoServer.system.uri}
        predicates:
        - Path=/api/search/**

      - id:fungo-game-system-5:
        uri:  ${fungoServer.system.uri}
        predicates:
        - Path=/api/mine/**

